### ISSUE TITLE
decoding associative array of int values

### ISSUE THREAD

**Issue by sneakyimp** [sneakyimp/amfext#3]
So based on test 005, I devised this test script:

``` php
<?php
$dir = dirname(__FILE__);
$v = array('a' => 1, 'b' => 3);
$encoded = amf_encode($v);
echo "--encoded--\n";
var_dump(bin2hex($encoded));
echo "--\n";

$decoded = amf_decode($encoded);
echo "--decoded--\n";
var_dump($decoded);
echo "--\n";

if ($v === $decoded) {
        echo "original and decoded are strictly equal\n";
} else {
        echo "original and decoded are NOTE strictly equal\n";
}
```

the output says that encoding is correct (it matches exactly a flash-encoded array like this. there's something wrong with the decoder. here's the file output

```
--encoded--
string(22) "0901036104010362040301"
--
--decoded--
array(2) {
  ["a"]=>
  int(3)
  ["b"]=>
  int(3)
}
--
original and decoded are NOTE strictly equal
```

As you can see, the value of 3 has been assigned to both associative keys. might be due to some pointer abuse?

**Comment by sneakyimp** [comment]
This bug appears to have been introduced with our changes that fixed our memory leaks. Looks like we'll need to be allocating memory for assoc_val inside the loop after all?

**Comment by sneakyimp** [comment]
I believed I have fixed this with commit d5982f490c7717a505aece36b62a725d7585ce65. We had to do the MAKE_STD_ZVAL for assoc_val and also its dtor inside the associative key loop.

**Comment by Sean-Der** [comment]
This is fixed for me!

**Comment by sneakyimp** [comment]
I'll close this one then.
