### ISSUE TITLE
Fix encoding/decoding of hash + string refs

### ISSUE THREAD

**Issue by Sean-Der** [sneakyimp/amfext#6]
Currently deserializing `['a' => 'a']` will segfault.

I don't have the tools to confirm the serializing works, if I can get a test with some sample data that would really help.

**Comment by sneakyimp** [comment]
I have checked amf_encode's output for this associative array against that output by flash player and it appears that they match identically:

```
$ xxd /tmp/flash_testing.txt
0000000: 0901 0361 0600 01                        ...a...
```

I think the issue might be that the decoding process is not able to handle when associative array keys are sent by reference. I.e., AMF3 keeps a running array of all strings encountered so that if any string is encountered twice, it can be sent 'by reference' the second time instead of serializing the whole array again.

I probably won't be able to look into this today -- I've got to tackle some work for a client so I can pay some bills.

**Comment by sneakyimp** [comment]
> Currently deserializing ['a' => 'a'] will segfault.

I think this problem is fixed if we remove my zval_dtor(assoc_val) from the loop in amf_read_array.

Also, this didn't segfault on my machine when I ran this test on my machine today:

``` php
<?php
$dir = dirname(__FILE__);
$v = array('a' => 'a');
$encoded = amf_encode($v);
echo "--encoded--\n";
var_dump(bin2hex($encoded));
echo "--\n";

$decoded = amf_decode($encoded);
echo "--decoded--\n";
var_dump($decoded);
echo "--\n";

if ($v === $decoded) {
    echo "original and decoded are strictly equal\n";
} else {
    echo "original and decoded are NOT strictly equal\n";
}
```

I did get some warning-type output on stderr, but didn't see the word 'segfault' anywhere:

```
--encoded--
string(14) "09010361060001"
--
--decoded--
array(1) {
  ["a"]=>
  string(1) "Z"
}
--
original and decoded are NOT strictly equal
PHP Warning:  String is not zero-terminated (ZZI��) (source: /home/jaith/src/php-5.5.29/Zend/zend_execute.h:81) in Unknown on line 0

Warning: String is not zero-terminated (ZZI��) (source: /home/jaith/src/php-5.5.29/Zend/zend_execute.h:81) in Unknown on line 0
[Mon Oct  5 08:22:10 2015]  Script:  '/home/jaith/src/php-5.5.29/ext/amf/jta/t3.php'
---------------------------------------
/home/jaith/src/php-5.5.29/Zend/zend_execute.h(81) : Block 0x7fdbb97c04b0 status:
/home/jaith/src/php-5.5.29/Zend/zend_variables.c(36) : Actual location (location was relayed)
Beginning:      Cached
Freed (invalid)
    Start:  OK
      End:  OK
---------------------------------------
```

**Comment by sneakyimp** [comment]
This bug appears to have been fixed in recent commits. I'm closing it.

**Comment by Sean-Der** [comment]
Hey @sneakyimp 

Sorry I got sick/burned out, so have been doing the bare minimum amount of work the past couple of days!

Sorry for the silence, amfext is still on my TODO list! I will comment on everything in the next couple of days

**Comment by sneakyimp** [comment]
> Sorry I got sick/burned out, so have been doing the bare minimum amount of work the past couple of days!

I _totally_ sympathize. I'm also kind of a helpless case. Whenever you are ready.

> Sorry for the silence, amfext is still on my TODO list! I will comment on everything in the next couple of days

No rush! I have been looking into firing up some virtual machines as you suggested, although I'm leaning toward VirtualBox as I find it a bit sketchy to be running other people's VM snapshots. I'm hoping that once I get the code compiling on these VMs that I'll be able to get **make test** running so I can send you some proper test files.

**VERY IMPORTANT:** The code I've sent may be ugly or look strange, but it has been serializing and unserializing like a champ from what I can tell. Take a peek in the issues where I talk about the memory leaks. And keep your eyes peeled for some proper test.phpt files.
